name: paint_codex
description: "Paint Codex"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  freezed_annotation: ^2.4.4
  json_annotation: 4.9.0
  window_size: 0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  build_runner: 2.4.15
  freezed: 2.5.8
  json_serializable: 6.9.4

flutter:
  uses-material-design: true
  assets:
    - assets/paints.json
